spring.application.name=shift
# H2データベースを使う設定
spring.datasource.url=jdbc:h2:mem:shiftdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2の管理画面（ブラウザでDBの中身を見られる）を有効にする
spring.h2.console.enabled=true

# JPAの設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 起動時に data.sql を実行してくれる設定
spring.jpa.defer-datasource-initialization=true